hidden_dim: 128
latent_dim: 6
batch_size: 64  # due to triplet loss effective batch size is 3 times this value
epochs: 1000
learning_rate: 0.0001
device: 'cuda'
verbose: False
margin: 1.0
target_label: "family"
weight_triplet_loss: 2.0
weight_custom_loss: 0.05

# early stop
use_early_stop: False
early_stop_patience: 100
early_stop_min_delta: 1.0
early_stop_metric: "h"
early_stop_mode: "min"
save_best_model: True
